workflows:
  ios-internal:
    name: iOS Internal
    integrations:
      app_store_connect: asc
    environment:
      groups:
        - Schumann
      xcode: latest
      node: 20
    scripts:
      # Sanity / Info
      - 'echo "BUNDLE_ID=$BUNDLE_ID  TEAM_ID=$TEAM_ID"'
      - '[[ -n "$BUNDLE_ID" && -n "$TEAM_ID" ]] || { echo "Env-Variablen fehlen"; exit 1; }'
      - 'echo "Node: $(node -v)  NPM: $(npm -v)"'

      # Build Web + iOS Gerüst
      - npm ci
      - npm run build
      - npx cap add ios || true
      - npx cap sync ios

      # Pods
      - cd ios/App && pod repo update
      - cd ios/App && pod install --repo-update
      - cd ../../

      # 🔐 Code signing (korrekte Reihenfolge!)
      - keychain initialize
      - keychain add-certificates
      - app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - xcode-project use-profiles

      # Export-Options
      - |
        cat > /Users/builder/export_options.plist <<'PLIST'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0"><dict>
          <key>method</key><string>app-store</string>
        </dict></plist>
        PLIST

      # Archiv & Export
      - xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App" --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
