workflows:
  ios-internal:
    name: iOS Internal
    integrations:
      app_store_connect: asc
    environment:
      groups:
        - Schumann
      ios_signing:
        distribution_type: app_store
        bundle_identifier: de.svschumann.schadenaufnahme
      xcode: latest
      node: 20
    scripts:
      - npm ci
      - npm run build
      - npx cap add ios || true
      - npx cap sync ios
      - cd ios/App && pod install --repo-update && cd ../..
      - xcode-project use-profiles
      - |
        PLIST="ios/App/App/Info.plist"
        BN="${BUILD_NUMBER:-${CM_BUILD_ID:-$(date +%Y%m%d%H%M)}}"
        echo "Set CFBundleVersion -> $BN"
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BN" "$PLIST"
      - xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
