workflows:
  ios-internal:
    name: iOS Internal

    # <-- DAS verlangt Codemagic, wenn du unten auth: integration nutzt
    integrations:
      app_store_connect: asc   # "asc" = Name deiner Team-Integration

    environment:
      groups:
        - Schumann             # deine Variablen-Gruppe (BUNDLE_ID/TEAM_ID, falls genutzt)
      ios_signing:
        distribution_type: app_store
        bundle_identifier: de.svschumann.schadenaufnahme
      xcode: latest
      node: 20

    scripts:
      - npm ci
      - npm run build
      - npx cap add ios || true
      - npx cap sync ios
      - cd ios/App && pod install --repo-update && cd ../..
      - xcode-project use-profiles
      - xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration       # -> erfordert den Block integrations: ... (s.o.)
        submit_to_testflight: true
