workflows:
  ios-internal:
    name: iOS Internal
    integrations:
      app_store_connect: asc
    environment:
      vars:
        APP_ID: "de.svschumann.schadenaufnahme"
      xcode: latest
      node: 20
    scripts:
      - 'echo "Node: $(node -v)  NPM: $(npm -v)"'
      - npm ci
      - npm run build
      - npx cap add ios
      - ls -la
      - '[ -d ios ] || { echo "ERROR: ios/ wurde nicht erstellt"; exit 1; }'
      - '[ -d ios/App ] || { echo "ERROR: ios/App fehlt"; exit 1; }'
      - npx cap sync ios
      - cd ios/App
      - pod repo update
      - pod install --repo-update
      - cd ../..
      - xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App" --archive-flags="-destination '\''generic/platform=iOS'\''"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
